# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `font-awesome-sass` gem.
# Please instead update this file by running `tapioca generate`.

# typed: true

module FontAwesome
end

module FontAwesome::Sass
  class << self
    def assets_path; end
    def deprecated_sass?; end
    def fonts_path; end
    def gem_path; end
    def load!; end
    def rails?; end
    def sprockets?; end
    def stylesheets_path; end

    private

    def register_rails_engine; end
    def register_sprockets; end
  end
end

module FontAwesome::Sass::Rails
end

class FontAwesome::Sass::Rails::Engine < ::Rails::Engine
end

class FontAwesome::Sass::Rails::Railtie < ::Rails::Railtie
end

module FontAwesome::Sass::Rails::ViewHelpers
  def icon(style, name, text = T.unsafe(nil), html_options = T.unsafe(nil)); end
end
