# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mini_portile` gem.
# Please instead update this file by running `tapioca generate`.

# typed: true

class MiniPortile
  def initialize(name, version); end

  def activate; end
  def compile; end
  def configure; end
  def configure_options; end
  def configure_options=(_); end
  def configured?; end
  def cook; end
  def download; end
  def downloaded?; end
  def extract; end
  def files; end
  def files=(_); end
  def host; end
  def host=(_); end
  def install; end
  def installed?; end
  def logger; end
  def logger=(_); end
  def name; end
  def original_host; end
  def patch; end
  def patch_files; end
  def patch_files=(_); end
  def path; end
  def target; end
  def target=(_); end
  def version; end

  private

  def archives_path; end
  def computed_options; end
  def configure_defaults; end
  def configure_prefix; end
  def detect_host; end
  def download_file(url, full_path, count = T.unsafe(nil)); end
  def download_file_ftp(uri, full_path); end
  def download_file_http(url, full_path, count = T.unsafe(nil)); end
  def execute(action, command); end
  def extract_file(file, target); end
  def gcc_cmd; end
  def log_file(action); end
  def make_cmd; end
  def message(text); end
  def newer?(target, checkpoint); end
  def output(text = T.unsafe(nil)); end
  def port_path; end
  def tar_compression_switch(filename); end
  def tar_exe; end
  def tmp_path; end
  def which(cmd); end
  def with_tempfile(filename, full_path); end
  def work_path; end
end
