# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mono_logger` gem.
# Please instead update this file by running `tapioca generate`.

# typed: true

class MonoLogger < ::Logger
  def initialize(logdev, shift_age = T.unsafe(nil), shift_size = T.unsafe(nil)); end
end

class MonoLogger::LocklessLogDevice < ::Logger::LogDevice
  def initialize(log = T.unsafe(nil)); end

  def close; end
  def write(message); end

  private

  def add_log_header(file); end
  def create_logfile(filename); end
  def open_logfile(filename); end
end

MonoLogger::VERSION = T.let(T.unsafe(nil), String)
