# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubocop-ruby2_1` gem.
# Please instead update this file by running `tapioca generate`.

# typed: true

module Rubocop
end

module Rubocop::Ruby21
end

Rubocop::Ruby21::VERSION = T.let(T.unsafe(nil), String)
