# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `vegas` gem.
# Please instead update this file by running `tapioca generate`.

# typed: true

module Vegas
end

class Vegas::Runner
  def initialize(app, app_name, set_options = T.unsafe(nil), runtime_args = T.unsafe(nil), &block); end

  def announce_port_attempted; end
  def app; end
  def app_dir; end
  def app_name; end
  def args; end
  def check_for_running(path = T.unsafe(nil)); end
  def daemon_execute; end
  def daemonize!; end
  def filesystem_friendly_app_name; end
  def find_port; end
  def host; end
  def kill!; end
  def launch!(specific_url = T.unsafe(nil), path = T.unsafe(nil)); end
  def load_config_file(config_path); end
  def log_file; end
  def logger; end
  def options; end
  def pid_file; end
  def port; end
  def port_open?(check_url = T.unsafe(nil)); end
  def quoted_app_name; end
  def rack_handler; end
  def run!; end
  def start(path = T.unsafe(nil)); end
  def status; end
  def url; end
  def url_file; end
  def write_url; end

  private

  def define_options; end
  def delete_pid!; end
  def kill_command; end
  def kill_commands; end
  def setup_rack_handler; end

  class << self
    def logger; end
    def logger=(logger); end
  end
end

Vegas::Runner::HOST = T.let(T.unsafe(nil), String)

Vegas::Runner::PORT = T.let(T.unsafe(nil), Fixnum)

Vegas::Runner::ROOT_DIR = T.let(T.unsafe(nil), String)

Vegas::VERSION = T.let(T.unsafe(nil), String)
