# typed: strict
  SPOT_TOPIC=35
  TEST_SPOT_TOPIC=43
  ALERT_TOPIC=1
  TEST_ALERT_TOPIC=44
  HELP_TOPIC=39
  FAQ_TOPIC=40
  NEWS_TOPIC=4
  AWARDS_TOPIC=42
  PHOTO_TOPIC=41
  ACCESS_INFO="/posts/831/"
