do_get_spots:
  every: 60s
  class: GetSpots
  args:
  description: Runs the perform method in GetSpots

do_get_external_activation:
  every: 300s
  class: UpdateExternalActivations
  args:
  description: Runs the perform method in UpdateExternalActivations

do_export_assets:
  every: 2592000s
  class: ExportAssets
  args:
  description: Runs the perform method in ExportAssets monthly

do_export_sitemaps:
  every: 2592000s
  class: ExportSitemaps
  args:
  description: Runs the perform method in ExportSitemaps monthly

do_tidy_user_agents:
  cron: 40 1 * * *
  class: TidyUserAgentsJob
  args:
  description: Runs the perform method in TidyUserAgentsJob  daily

do_export_bad_ips:
  cron: 50 1 * * *
  class: ExportBadIpsJob
  description: Exports malicious IPs to /tmp/bad_ips.txt for ipset processing
