do_get_spots:
  every: 60s
  class: GetSpots
  args:
  description: Runs the perform method in GetSpots

do_get_external_activation:
  every: 300s
  class: UpdateExternalActivations
  args:
  description: Runs the perform method in UpdateExternalActivations

do_export_assets:
  every: 2592000s
  class: ExportAssets
  args:
  description: Runs the perform method in ExportAssets monthly

do_export_sitemaps:
  every: 2592000s
  class: ExportSitemaps
  args:
  description: Runs the perform method in ExportSitemaps monthly

do_tidy_user_agents:
  cron: 40 1 * * *
  class: TidyUserAgentsJob
  args:
  description: Runs the perform method in TidyUserAgentsJob  daily

do_import_siota:
  cron: 0 0 1 * *
  class: UpdateSiota
  args:
  description: Runs the perform method in UpdateSiota  monthly

do_import_sota:
  cron: 15 0 1 * *
  class: UpdateSota
  args:
  description: Runs the perform method in UpdateSota  monthly

do_import_illw:
  cron: 30 0 1 * *
  class: UpdateIllw
  args:
  description: Runs the perform method in UpdateIllw  monthly
