# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#User.create(callsign: "gw7nvw", firstname: "Matt", lastname: "Briggs", email: "mattbriggs@yahoo.com", activated: true, is_active: true, is_admin: true,  is_modifier: true, password: "dummy", password_confirmation: "dummy")

#Projection.create(id: 2193, name: "NZTM2000", proj4: "+proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +towg", wkt: "", epsg: 2193)
#Projection.create(id: 4326, name: "WGS84", proj4: "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs", wkt: "", epsg: 4326)
#Projection.create(id: 27200, name: "NZMG49", proj4: "+proj=nzmg +lat_0=-41 +lon_0=173 +x_0=2510000 +y_0=6023150 +ellps=intl +datum=nzgd49 +units=m +no_defs", wkt: "", epsg: 27200)
#Projection.create(id: 27291, name: "NIYG", proj4: "+proj=tmerc +lat_0=-39 +lon_0=175.5 +k=1 +x_0=274319.5243848086 +y_0=365759.3658464114 +ellps=intl +datum=nzgd49 +to_meter=0.9143984146160287 +no_defs", wkt: "", epsg: 27291)
#Projection.create(id: 27292, name: "SIYG", proj4: "+proj=tmerc +lat_0=-44 +lon_0=171.5 +k=1 +x_0=457199.2073080143 +y_0=457199.2073080143 +ellps=intl +datum=nzgd49 +to_meter=0.9143984146160287 +no_defs", wkt: "", epsg: 27292)
#Projection.create(id: 900913, name: "GOOGLE", proj4: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs", wkt: "", epsg: 900913)
##Timezone.create(name: "Pacific/Auckland", description: "Pacific / New Zealand / Auckland", difference: 13)
#Timezone.create(name: "UTC", description: "UTC", difference: 0)
#Timezone.create(name: "Pacific/Chatham", description: "Pacific / New Zealand / Chatham Islands", difference: 13.45)

#Maplayer.create(name: "NZTM Topo 2019", baseurl: "http://au.mapspast.org.nz/topo50-2019/", basemap: "mapspast", minzoom: 0, maxzoom: 10, imagetype: "png")
#Maplayer.create(name: "Public Access Land", baseurl: "http://au.mapspast.org.nz/pal-2193/", basemap: "mapspast", minzoom: 0, maxzoom: 10, imagetype: "png")
#Maplayer.create(name: "(LINZ) Topo50 latest", baseurl: "http://tiles-a.data-cdn.linz.govt.nz/services;key=d8c83efc690a4de4ab067eadb6ae95e4/tiles/v4/layer=767/EPSG:2193/", basemap: "linz", minzoom: 0, maxzoom: 16, imagetype: "png")
#Maplayer.create(name: "(LINZ) Airphoto latest", baseurl: "http://tiles-a.data-cdn.linz.govt.nz/services;key=d8c83efc690a4de4ab067eadb6ae95e4/tiles/v4/set=2/EPSG:2193/", basemap: "linz", minzoom: 0, maxzoom: 16, imagetype: "png")


#ps=Place.find_by_sql [ "select * from places where place_type='Hut'"]
#ps.each do |p|
#  Hut.create(name: p.name, description: p.description, location: p.location, x: p.x, y: p.y, altitude: p.altitude, is_active: true, routeguides_link: 'http://routeguides.co.nz/places/'+p.id.to_s)
#end

#pull in docparks 
#Park.update_table

#assign huts to parks
#Hut.assign_all_parks

#add links
#Hut.update_links

SotaRegion.create(dxcc: "ZL1", region: "AK")
SotaRegion.create(dxcc: "ZL1", region: "WL")
SotaRegion.create(dxcc: "ZL1", region: "WK")
SotaRegion.create(dxcc: "ZL1", region: "TN")
SotaRegion.create(dxcc: "ZL1", region: "NL")
SotaRegion.create(dxcc: "ZL1", region: "MW")
SotaRegion.create(dxcc: "ZL1", region: "HB")
SotaRegion.create(dxcc: "ZL1", region: "GI")
SotaRegion.create(dxcc: "ZL1", region: "BP")
SotaRegion.create(dxcc: "ZL3", region: "CB")
SotaRegion.create(dxcc: "ZL3", region: "FL")
SotaRegion.create(dxcc: "ZL3", region: "MB")
SotaRegion.create(dxcc: "ZL3", region: "OT")
SotaRegion.create(dxcc: "ZL3", region: "SL")
SotaRegion.create(dxcc: "ZL3", region: "TM")
SotaRegion.create(dxcc: "ZL3", region: "WC")
SotaRegion.create(dxcc: "ZL7", region: "CI")
SotaRegion.create(dxcc: "ZL8", region: "MI")
SotaRegion.create(dxcc: "ZL8", region: "RI")
SotaRegion.create(dxcc: "ZL9", region: "DI")
SotaRegion.create(dxcc: "ZL9", region: "AD")
SotaRegion.create(dxcc: "ZL9", region: "AI")
SotaRegion.create(dxcc: "ZL9", region: "CI")
SotaRegion.create(dxcc: "ZL9", region: "AN")

Timezone.create({"id"=>3, "name"=>"UTC", "description"=>"UTC", "difference"=>0})
Timezone.create({"id"=>1, "name"=>"Pacific/Auckland", "description"=>"Pacific / New Zealand / Auckland (NZDT/NZST)", "difference"=>13})
Timezone.create({"id"=>4, "name"=>"Pacific/Chatham", "description"=>"Pacific / New Zealand / Chatham Islands", "difference"=>nil})
AssetType.create({"id"=>28, "name"=>"lake", "table_name"=>"Lake", "has_location"=>true, "has_boundary"=>true, "index_name"=>"code", "display_name"=>"Lake", "fields"=>"info_origin", "pnp_class"=>"ZLOTA", "keep_score"=>true, "min_qso"=>2, dist_buffer: 500})
AssetType.create({"id"=>26, "name"=>"pota park", "table_name"=>"PotaPark", "has_location"=>true, "has_boundary"=>true, "index_name"=>"reference", "display_name"=>" POTA Park", "fields"=>"", "pnp_class"=>"POTA", "keep_score"=>false, "min_qso"=>10})
AssetType.create({"id"=>27, "name"=>"wwff park", "table_name"=>"WwffPark", "has_location"=>true, "has_boundary"=>true, "index_name"=>"code", "display_name"=>"WWFF Park", "fields"=>"", "pnp_class"=>"WWFF", "keep_score"=>false, "min_qso"=>10})
AssetType.create({"id"=>22, "name"=>"park", "table_name"=>"Park", "has_location"=>true, "has_boundary"=>true, "index_name"=>"code", "display_name"=>"Park", "fields"=>"", "pnp_class"=>"ZLOTA", "keep_score"=>true, "min_qso"=>4})
AssetType.create({"id"=>21, "name"=>"all", "table_name"=>"Asset", "has_location"=>true, "has_boundary"=>true, "index_name"=>"code","display_name"=>"All", "fields"=>"", "pnp_class"=>"", "keep_score"=>false, "min_qso"=>1})
AssetType.create({"id"=>23, "name"=>"hut", "table_name"=>"Hut", "has_location"=>true, "has_boundary"=>false, "index_name"=>"code", "display_name"=>"Hut", "fields"=>"", "pnp_class"=>"ZLOTA", "keep_score"=>true, "min_qso"=>1})
AssetType.create({"id"=>25, "name"=>"summit", "table_name"=>"SotaPeak", "has_location"=>true, "has_boundary"=>false, "has_elevation"=>true, "index_name"=>"summit_code", "display_name"=>"SOTA Summit", "fields"=>nil, "pnp_class"=>"", "keep_score"=>nil, "min_qso"=>4, "ele_buffer"=>25})
AssetType.create({"id"=>30, "name"=>"lighthouse", "table_name"=>"Lighthouse", "has_location"=>true, "has_boundary"=>true, "index_name"=>"code","display_name"=>"Lighthouse", "fields"=>nil, "pnp_class"=>"ZLOTA", "keep_score"=>true, "min_qso"=>4})
AssetType.create({"id"=>31, "name"=>"hump", "table_name"=>"Hump", "has_location"=>true, "has_boundary"=>false, "has_elevation"=>true, "index_name"=>"code", "display_name"=>"HEMA Hump", "fields"=>"", "pnp_class"=>"HEMA", "keep_score"=>true, "min_qso"=>4, "ele_buffer"=>25})
AssetType.create({"id"=>24, "name"=>"island", "table_name"=>"Island", "has_location"=>true, "has_boundary"=>true, "index_name"=>"code", "display_name"=>"Island", "fields"=>"status,info_ref,info_origin,info_note", "pnp_class"=>"ZLOTA", "keep_score"=>true, "min_qso"=>5})
AwardThreshold.create({"id"=>1, "threshold"=>10, "name"=>"bronze"})
AwardThreshold.create({"id"=>2, "threshold"=>30, "name"=>"silver"})
AwardThreshold.create({"id"=>3, "threshold"=>100, "name"=>"gold"})
AwardThreshold.create({"id"=>4, "threshold"=>300, "name"=>"diamond"})
AwardThreshold.create({"id"=>5, "threshold"=>1000, "name"=>"platinum"})
Award.create({"id"=>15, "name"=>"Activated all district (huts)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>true, "chased"=>false, "programme"=>"hut", "all_district"=>true, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>18, "name"=>"Activated all district (islands)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>true, "chased"=>false, "programme"=>"island", "all_district"=>true, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>14, "name"=>"Activated all district (lakes)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>true, "chased"=>false, "programme"=>"lake", "all_district"=>true, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>16, "name"=>"Activated all district (summits)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>true, "chased"=>false, "programme"=>"summit", "all_district"=>true, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>17, "name"=>"Activated all district (parks)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>true, "chased"=>false, "programme"=>"park", "all_district"=>true, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>19, "name"=>"Activated all region (hut)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>true, "chased"=>false, "programme"=>"hut", "all_district"=>false, "all_region"=>true, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>20, "name"=>"Activated all region (park)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>true, "chased"=>false, "programme"=>"park", "all_district"=>false, "all_region"=>true, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>7, "name"=>"Hut Chaser", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>true, "activated"=>false, "chased"=>true, "programme"=>"hut", "all_district"=>false, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>9, "name"=>"Lake Chaser", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>true, "activated"=>false, "chased"=>true, "programme"=>"lake", "all_district"=>false, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>11, "name"=>"Park Chaser", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>true, "activated"=>false, "chased"=>true, "programme"=>"park", "all_district"=>false, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>13, "name"=>"Island Chaser", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>true, "activated"=>false, "chased"=>true, "programme"=>"island", "all_district"=>false, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>21, "name"=>"Activated all region (island)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>true, "chased"=>false, "programme"=>"island", "all_district"=>false, "all_region"=>true, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>22, "name"=>"Activated all region (lake)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>true, "chased"=>false, "programme"=>"lake", "all_district"=>false, "all_region"=>true, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>23, "name"=>"Activated all region (summit)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>true, "chased"=>false, "programme"=>"summit", "all_district"=>false, "all_region"=>true, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>6, "name"=>"Hut Activator (qualified)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>true, "activated"=>true, "chased"=>false, "programme"=>"hut", "all_district"=>false, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>12, "name"=>"Island Activator (qualified)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>true, "activated"=>true, "chased"=>false, "programme"=>"island", "all_district"=>false, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>8, "name"=>"Lake Activator (qualified)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>true, "activated"=>true, "chased"=>false, "programme"=>"lake", "all_district"=>false, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>10, "name"=>"Park Activator (qualified)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>true, "activated"=>true, "chased"=>false, "programme"=>"park", "all_district"=>false, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>24, "name"=>"Activated all region (WWFF)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>true, "chased"=>false, "programme"=>"wwff park", "all_district"=>false, "all_region"=>true, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>25, "name"=>"Activated all region (POTA)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>true, "chased"=>false, "programme"=>"pota park", "all_district"=>false, "all_region"=>true, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>26, "name"=>"Chased all district (huts)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>false, "chased"=>true, "programme"=>"hut", "all_district"=>true, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>27, "name"=>"Chased all district (islands)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>false, "chased"=>true, "programme"=>"island", "all_district"=>true, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>28, "name"=>"Chased all district (lakes)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>false, "chased"=>true, "programme"=>"lake", "all_district"=>true, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>29, "name"=>"Chased all district (summits)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>false, "chased"=>true, "programme"=>"summit", "all_district"=>true, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>30, "name"=>"Chased all district (parks)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>false, "chased"=>true, "programme"=>"park", "all_district"=>true, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>31, "name"=>"Chased all region (hut)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>false, "chased"=>true, "programme"=>"hut", "all_district"=>false, "all_region"=>true, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>32, "name"=>"Chased all region (park)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>false, "chased"=>true, "programme"=>"park", "all_district"=>false, "all_region"=>true, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>33, "name"=>"Chased all region (island)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>false, "chased"=>true, "programme"=>"island", "all_district"=>false, "all_region"=>true, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>34, "name"=>"Chased all region (lake)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>false, "chased"=>true, "programme"=>"lake", "all_district"=>false, "all_region"=>true, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>35, "name"=>"Chased all region (summit)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>false, "chased"=>true, "programme"=>"summit", "all_district"=>false, "all_region"=>true, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>36, "name"=>"Chased all region (WWFF)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>false, "chased"=>true, "programme"=>"wwff park", "all_district"=>false, "all_region"=>true, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>37, "name"=>"Chased all region (POTA)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>false, "chased"=>true, "programme"=>"pota park", "all_district"=>false, "all_region"=>true, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>38, "name"=>"Lake Uniques (bagged)", "description"=>"Bagged (activated or chased) distinct lakes", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>true, "activated"=>false, "chased"=>false, "programme"=>"lake", "all_district"=>false, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>39, "name"=>"Lake Completes", "description"=>"Activate and chase same lakes", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>false, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>true, "activated"=>true, "chased"=>true, "programme"=>"lake", "all_district"=>false, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>40, "name"=>"Park Uniques (bagged)", "description"=>"Distinct parks chased or activated.", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>true, "activated"=>false, "chased"=>false, "programme"=>"park", "all_district"=>false, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>42, "name"=>"Lighthouse Chaser", "description"=>"Chasing Lighthouses", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>true, "activated"=>false, "chased"=>true, "programme"=>"lighthouse", "all_district"=>false, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>43, "name"=>"Lighthouse Uniques (bagged)", "description"=>"", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>true, "activated"=>false, "chased"=>false, "programme"=>"lighthouse", "all_district"=>false, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>41, "name"=>"Lighthouse Activator (qualified)", "description"=>"Activation of lighthouses", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>true, "activated"=>true, "chased"=>false, "programme"=>"lighthouse", "all_district"=>false, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>44, "name"=>"Activated all region (lighthouses)", "description"=>"Activated all lighthouses in a region", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>true, "chased"=>false, "programme"=>"lighthouse", "all_district"=>false, "all_region"=>true, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>45, "name"=>"Chased all region (lighthouses)", "description"=>"Chased all lighthouses in a region", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>false, "activated"=>false, "chased"=>true, "programme"=>"lighthouse", "all_district"=>false, "all_region"=>true, "all_programme"=>false, "p2p"=>false})
Award.create({"id"=>46, "name"=>"Hut Uniques (bagged)", "description"=>"Bagged (activated or chased) distinct huts", "email_text"=>"", "user_qrp"=>false, "contact_qrp"=>nil, "is_active"=>true, "createdBy_id"=>4, "allow_repeat_visits"=>false, "count_based"=>true, "activated"=>false, "chased"=>false, "programme"=>"hut", "all_district"=>false, "all_region"=>false, "all_programme"=>false, "p2p"=>false})
Projection.create({"id"=>2193, "name"=>"NZTM2000", "proj4"=>"+proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +towg", "wkt"=>"", "epsg"=>2193, "createdBy_id"=>nil})
Projection.create({"id"=>4326, "name"=>"WGS84", "proj4"=>"+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs", "wkt"=>"", "epsg"=>4326})
Projection.create({"id"=>27200, "name"=>"NZMG49", "proj4"=>"+proj=nzmg +lat_0=-41 +lon_0=173 +x_0=2510000 +y_0=6023150 +ellps=intl +datum=nzgd49 +units=m +no_defs", "wkt"=>"", "epsg"=>27200})
Projection.create({"id"=>27291, "name"=>"NIYG", "proj4"=>"+proj=tmerc +lat_0=-39 +lon_0=175.5 +k=1 +x_0=274319.5243848086 +y_0=365759.3658464114 +ellps=intl +datum=nzgd49 +to_meter=0.9143984146160287 +no_defs", "wkt"=>"", "epsg"=>27291})
Projection.create({"id"=>27292, "name"=>"SIYG", "proj4"=>"+proj=tmerc +lat_0=-44 +lon_0=171.5 +k=1 +x_0=457199.2073080143 +y_0=457199.2073080143 +ellps=intl +datum=nzgd49 +to_meter=0.9143984146160287 +no_defs", "wkt"=>"", "epsg"=>27292})
Projection.create({"id"=>900913, "name"=>"GOOGLE", "proj4"=>"+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs", "wkt"=>"", "epsg"=>900913})
Projection.create({"id"=>-99, "name"=>"Maidenhead", "proj4"=>"+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs", "wkt"=>"", "epsg"=>4326})
AdminSettings.create()
